[view_keys]

[spend_keys]

[payment_addrs]

[keys]
bertha-key = "unencrypted:00d1e8b9b4c6b59a30c0583fe2a6b58ddcd70040d8c2e139c00f0c3c49b081befb"
daewon = "unencrypted:009aacade025eb6dc8d5ca370e55a23c3e31d0cbe20461cb4f43ee504eacd5e5b0"
christel-key = "unencrypted:00dad772fa2c9c180b4c039d3bb389ee2e8bc79a0578cd2b054d3896d3ad18e2a6"
masp-key = "unencrypted:00d1ab26c560b354151d71f4228097f406f097ac71f23630daccd21da165e2ea2a"
faucet-key = "unencrypted:0079b5f7bf9a7634c3ab1f7853bc196283e4190422aa21085a0dbc548e554e0da2"
albert-key = "unencrypted:00438a5734f543e7c78e55eb329a00d5a3656c85da702e710fa10130675949952e"

[addresses]
bertha-key = "atest1d9khqw368pq52sj9xgmrys2yxg6nys3kgcunsve4ggu5vdj9gdz5xsfjgg6yzd2y8pz5v33cdzqqlw"
faucet-key = "atest1d9khqw36gdprj3fs8q6yx33cxvm52dpexycrqs3ngg6yzwzrxcuygsej8qensseh8qm52v2zsd2hvy"
christel-key = "atest1d9khqw36g4zrzvjxgyenjvp4x3pnv33egvuyz3f3xpp5233sgfzrjvekxs6nvdpngycny3f5hq007s"
pos = "atest1v9hx7w362pex7mmxyphkvgznw3skkefqyqszqgpqyqszqgpqyqszqgpqyqszqgpqyqszqgpqq8ylv7"
masp-key = "atest1d9khqw36xqcrgwzzx5u52wpexgu5zdfeg56yyvphxeryvd6pgsunzvpcxquygwpcxfznwdpj8y8zsz"
faucet = "atest1v4ehgw36gyerxv6xgyunqv3egsmnv3pj8quny3fc8prrs32rg4qnxv2ygser2djxgcmnzv2y3dnxyq"
governance = "atest1v9hx7w36gahhvetjdeskucm9yqszqgpqyqszqgpqyqszqgpqyqszqgpqyqszqgpqyqszqgpq5a20qt"
albert-key = "atest1d9khqw36xpzrzs2xxgunyve5x5erjdpk8pprvw2x8y65gvpjxdprxvjrxye5vs34xueyxd6ztzejmv"
pos_slash_pool = "atest1v9hx7w362pex7mmxyphkvgznw3skkefq2dkxzumgypgx7mmvyqszqgpqyqszqgpqyqszqgpqecxumt"
bertha = "atest1v4ehgw36gepnssfeggmnjdzpgye52wfegfrrv33nggerxdpngc6rvwpeg3p5xsej89z5gsfcyquyd0"
daewon = "atest1d9khqw36xvcrq3fsxymngvf4xfpr2d6xxscyv3f4xpzr2sfhxdpnjwzxxpry2sfk8qmrzv2p0ywt9c"
validator-0 = "atest1v4ehgw36xepngd2rxsmrjwfh8qmyxv3jgsu5ydjpxgmr2d3s8q6ngvfkxgerwsf4g5mrxd3j2pc5u5"
kartoffel = "atest1v4ehgw36gep5ysecxq6nyv3jg3zygv3e89qn2vp48pryxsf4xpznvve5gvmy23fs89pryvf5a6ht90"
btc = "atest1v4ehgw36xdzryve5gsc52veeg5cnsv2yx5eygvp38qcrvd29xy6rys6p8yc5xvp4xfpy2v694wgwcp"
eth = "atest1v4ehgw36xqmr2d3nx3ryvd2xxgmrq33j8qcns33sxezrgv6zxdzrydjrxveygd2yxumrsdpsf9jc2p"
masp = "atest1v4ehgw36xaryysfsx5unvve4g5my2vjz89p52sjxxgenzd348yuyyv3hg3pnjs35g5unvde4ca36y5"
nam = "atest1v4ehgw36x3prswzxggunzv6pxqmnvdj9xvcyzvpsggeyvs3cg9qnywf589qnwvfsg5erg3fkl09rg5"
albert = "atest1v4ehgw36gfpy2vp4gfryywfsxym5gs338y65gse4xgeyydjzxepnqdzrxdqnqwfhxcmnzw2p762kje"
dot = "atest1v4ehgw368quy2vjpgvcyxdpexep52sj9xfqn2veeggu5gvfcgg6yys6z8y6rsd35gfpr2de3c3wspr"
eth_bridge = "atest1v9hx7w36g42ysgzzwf5kgem9ypqkgerjv4ehxgpqyqszqgpqyqszqgpqyqszqgpqyqszqgpq8f99ew"
schnitzel = "atest1v4ehgw36xue5xvf5xvuyzvpjx5un2v3k8qeyvd3cxdqns32p89rrxd6xx9zngvpegccnzs699rdnnt"
apfel = "atest1v4ehgw36gfryydj9g3p5zv3kg9znyd358ycnzsfcggc5gvecgc6ygs2rxv6ry3zpg4zrwdfeumqcz9"
christel = "atest1v4ehgw36xcursv35g5myvd2xgyurzdzyg3zny3fcxpz5yw2r89ry2d3sg9rygv3jx4qny3zxhn4zsa"

[pkhs]
ED12FA39054C6F9C8AE10CEF0BD93645643A12E4 = "christel-key"
8AEBE262AD252B6F9835B9F6ECECA2B4A5D8EFF8 = "bertha-key"
300E0174152B57F40FE50D5A73C98F0FEA68611A = "daewon"
0D1AF29234529468B69F95D023B32C13FB572C7B = "albert-key"
0048B59E8929A59E4B076FF7AD910808D882E742 = "masp-key"
CB9E084CF837E49100B3B4A8C68DC2838C787E1B = "faucet-key"
